import Vocabulary from "./pages/Vocabulary"


function App() {
  const vocabularyData = [


    { arabic:' رَسُوْلٌ ', bengali: ' রাসুল ', category: ' islamic ', difficulty: 'easy' },
{ arabic:' خَلِيْفَةٌ ', bengali: ' খলীফা ', category: ' islamic ', difficulty: 'easy' },
{ arabic:' رَازِقٌ ', bengali: ' রিযিকদাতা ', category: ' islamic ', difficulty: 'easy' },
{ arabic:' بَائِسٌ ', bengali: ' নিঃস্ব ', category: ' human_adj ', difficulty: 'hard' },
{ arabic:' مُنِيْرٌ ', bengali: ' আলোদানকারী ', category: ' gen_adj ', difficulty: 'medium' },
{ arabic:' كَاتِبٌ ', bengali: ' লেখক ', category: ' profession ', difficulty: 'easy' },
{ arabic:' أَمِيْنٌ ', bengali: ' বিশ্বস্ত ', category: ' human_adj ', difficulty: 'easy' },
{ arabic:' أُسْتَاذٌ ', bengali: ' অধ্যাপক ', category: ' profession ', difficulty: 'medium' },
{ arabic:' سَمَاءٌ ', bengali: ' আকাশ ', category: ' nature ', difficulty: 'easy' },
{ arabic:' أَرْضٌ ', bengali: ' পৃথিবী ', category: ' nature ', difficulty: 'easy' },
{ arabic:' خَالَةٌ ', bengali: ' খালা ', category: ' relatives ', difficulty: 'easy' },
{ arabic:' شَهْرٌ ', bengali: ' মাস ', category: ' time ', difficulty: 'easy' },
{ arabic:' أُسْبُوْعٌ ', bengali: ' সপ্তাহ ', category: ' time ', difficulty: 'easy' },
{ arabic:' يَوْمٌ ', bengali: ' দিন ', category: ' time ', difficulty: 'easy' },
{ arabic:' سَنَةٌ ', bengali: ' বছর ', category: ' time ', difficulty: 'easy' },
{ arabic:' أَخٌ ', bengali: ' ভাই ', category: ' relatives ', difficulty: 'easy' },
{ arabic:' عَمٌّ ', bengali: ' চাচা ', category: ' relatives ', difficulty: 'easy' },
{ arabic:' جَدٌّ ', bengali: ' দাদা/নানা ', category: ' relatives ', difficulty: 'easy' },
{ arabic:' خَالٌ ', bengali: ' মামা ', category: ' relatives ', difficulty: 'easy' },
{ arabic:' اِسْمٌ ', bengali: ' নাম ', category: ' miscellaneous ', difficulty: 'easy' },
{ arabic:' نُوْرٌ ', bengali: ' আলো ', category: ' nature ', difficulty: 'easy' },
{ arabic:' ظُلْمَةٌ ', bengali: ' অন্ধকার ', category: ' nature ', difficulty: 'easy' },
{ arabic:' نِصْفٌ ', bengali: ' অর্ধেক ', category: ' measurement ', difficulty: 'easy' },
{ arabic:' مَوْتٌ ', bengali: ' মৃত্যু ', category: ' life_concept ', difficulty: 'easy' },
{ arabic:' حَيَةٌ ', bengali: ' জীবন ', category: ' life_concept ', difficulty: 'easy' },
{ arabic:' أَبٌ ', bengali: ' বাবা ', category: ' relatives ', difficulty: 'easy' },
{ arabic:' أُمٌّ ', bengali: ' মা ', category: ' relatives ', difficulty: 'easy' },
{ arabic:' أُخْتٌ ', bengali: ' বোন ', category: ' relatives ', difficulty: 'easy' },
{ arabic:' جَدَّةٌ ', bengali: ' দাদী/নানী ', category: ' relatives ', difficulty: 'easy' },
{ arabic:' حَفِيْدٌ ', bengali: ' নাতী ', category: ' relatives ', difficulty: 'hard' },
{ arabic:' صَاحِبٌ ', bengali: ' মালিক/সাথী ', category: ' relationship ', difficulty: 'hard' },
{ arabic:' بَقَرَةٌ ', bengali: ' গরু ', category: ' animal ', difficulty: 'easy' },
{ arabic:' حَقًّا ', bengali: ' সত্যি/আসলে ', category: ' expression ', difficulty: 'hard' },
{ arabic:' مَنْ ', bengali: ' কে/কার ', category: ' question_word ', difficulty: 'easy' },
{ arabic:' أَيٌّ ', bengali: ' কোন ', category: ' question_word ', difficulty: 'easy' },
{ arabic:' عِقْدٌ ', bengali: ' হার ', category: ' object ', difficulty: 'easy' },
{ arabic:' رَبٌّ ', bengali: ' রব ', category: ' islamic ', difficulty: 'easy' },
{ arabic:' جَامِعَةٌ ', bengali: ' বিশ্ববিদ্যালয় ', category: ' place ', difficulty: 'easy' },
{ arabic:' سَمِيْعٌ ', bengali: ' সর্বশ্রোতা ', category: ' divine_attribute ', difficulty: 'medium' },
{ arabic:' بَصِيْرٌ ', bengali: ' সর্বদ্রষ্টা ', category: ' divine_attribute ', difficulty: 'easy' },
{ arabic:' إِبْنٌ ', bengali: ' পুত্র ', category: ' relatives ', difficulty: 'easy' },
{ arabic:' مَلِكٌ ', bengali: ' রাজা ', category: ' position ', difficulty: 'easy' },
{ arabic:' حُسْنٌ ', bengali: ' সৌন্দর্য ', category: ' concept ', difficulty: 'hard' },
{ arabic:' مُفِيْدٌ ', bengali: ' উপকারী ', category: ' gen_adj ', difficulty: 'easy' },
{ arabic:' سِجْنٌ ', bengali: ' কারাগার ', category: ' place ', difficulty: 'medium' },
{ arabic:' بَارِعٌ ', bengali: ' দক্ষ ', category: ' human_adj ', difficulty: 'hard' },
{ arabic:' سَقْفٌ ', bengali: ' ছাদ ', category: ' house_part ', difficulty: 'easy' },
{ arabic:' كَلِمَة ', bengali: ' শব্দ ', category: ' language ', difficulty: 'medium' },
{ arabic:' كَلَام ', bengali: ' কথা ', category: ' language ', difficulty: 'medium' },
{ arabic:' نَتِيْجَة ', bengali: ' ফলাফল ', category: ' concept ', difficulty: 'medium' },
{ arabic:' قَرِيْب ', bengali: ' নিকটবর্তী ', category: ' position ', difficulty: 'medium' },
{ arabic:' بَعِيْد ', bengali: ' দূরবর্তী ', category: ' position ', difficulty: 'medium' },
{ arabic:' رَائِعٌ ', bengali: ' চমৎকার ', category: ' gen_adj ', difficulty: 'hard' },
{ arabic:' عَاصِمَة ', bengali: ' রাজধানী ', category: ' place ', difficulty: 'easy' },
{ arabic:' سَيْف ', bengali: ' তরবারি ', category: ' weapon ', difficulty: 'easy' },
{ arabic:' شُجَاعٌ ', bengali: ' সাহসী ', category: ' human_adj ', difficulty: 'hard' },
{ arabic:' جَبَانٌ ', bengali: ' ভীরু ', category: ' human_adj ', difficulty: 'easy' },
{ arabic:' ضَوْءٌ ', bengali: ' আলো ', category: ' nature ', difficulty: 'hard' },
{ arabic:' وَرْدَةٌ ', bengali: ' গোলাপ ', category: ' plant ', difficulty: 'easy' },
{ arabic:' ذَيْلٌ ', bengali: ' লেজ ', category: ' animal_part ', difficulty: 'hard' },
{ arabic:' مَالِحٌ ', bengali: ' লবনাক্ত ', category: ' taste ', difficulty: 'hard' },
{ arabic:' عَذْبٌ ', bengali: ' সুমিষ্ট ', category: ' taste ', difficulty: 'hard' },
{ arabic:' خُرْطُوْمٌ ', bengali: ' শুঁড় ', category: ' animal_part ', difficulty: 'medium' },
{ arabic:' رَائِحَةٌ ', bengali: ' ঘ্রাণ ', category: ' sense ', difficulty: 'medium' },
{ arabic:' مُهَنْدِسٌ ', bengali: ' প্রকৌশলি ', category: ' profession ', difficulty: 'easy' },
{ arabic:' مُنَوَّرٌ ', bengali: ' আলোকিত ', category: ' state ', difficulty: 'medium' },
{ arabic:' مُظْلِمٌ ', bengali: ' অন্ধকারাচ্ছন্ন ', category: ' state ', difficulty: 'medium' },
{ arabic:' جُنْدِيٌّ ', bengali: ' সৈনিক ', category: ' profession ', difficulty: 'medium' },
{ arabic:' سَاطِعٌ ', bengali: ' উজ্জ্বল ', category: ' light_quality ', difficulty: 'hard' },
{ arabic:' صَحِيْحٌ ', bengali: ' সঠিক ', category: ' quality ', difficulty: 'easy' },
{ arabic:' بِجَانِبِ ', bengali: ' পাশে ', category: ' position ', difficulty: 'easy' },
{ arabic:' تِلْقَاءَ ', bengali: ' দিকে ', category: ' direction ', difficulty: 'hard' },
{ arabic:' بَيْنَ ', bengali: ' মাঝে ', category: ' position ', difficulty: 'easy' },
{ arabic:' وَرَاءَ ', bengali: ' পিছনে ', category: ' position ', difficulty: 'easy' },
{ arabic:' عِنْدَ ', bengali: ' কাছে ', category: ' position ', difficulty: 'hard' },
{ arabic:' فَوْقَ ', bengali: ' উপরে ', category: ' position ', difficulty: 'easy' },
{ arabic:' تَحْتَ ', bengali: ' নীচে ', category: ' position ', difficulty: 'easy' },
{ arabic:' أَمَامَ ', bengali: ' সামনে ', category: ' position ', difficulty: 'easy' },
{ arabic:' خُبْزٌ ', bengali: ' রুটি ', category: ' food_drink ', difficulty: 'easy' },
{ arabic:' وَرَقَةٌ ', bengali: ' পাতা ', category: ' object ', difficulty: 'easy' },
{ arabic:' بَيْضَةٌ ', bengali: ' ডিম ', category: ' food_drink ', difficulty: 'easy' },
{ arabic:' خَالِصٌ ', bengali: ' খাটি ', category: ' quality ', difficulty: 'easy' },
{ arabic:' مَحَطَّةٌ ', bengali: ' স্টেশন ', category: ' place ', difficulty: 'hard' },
{ arabic:' مَطَارٌ ', bengali: ' বিমানবন্দর ', category: ' place ', difficulty: 'medium' },
{ arabic:' شَايٌ ', bengali: ' চা ', category: ' food_drink ', difficulty: 'medium' },
{ arabic:' قِطَارٌ ', bengali: ' ট্রেন ', category: ' transport ', difficulty: 'medium' },
{ arabic:' لَحْمٌ ', bengali: ' গোশত ', category: ' food_drink ', difficulty: 'easy' },
{ arabic:' مِدْفَعٌ ', bengali: ' কামান ', category: ' weapon ', difficulty: 'easy' },
{ arabic:' طَعَامٌ ', bengali: ' খাবার ', category: ' food_drink ', difficulty: 'easy' },
{ arabic:' جَرِيدَةٌ ', bengali: ' পত্রিকা ', category: ' object ', difficulty: 'easy' },
{ arabic:' شَجَرَةٌ ', bengali: ' গাছ ', category: ' plant ', difficulty: 'medium' },
{ arabic:' زَهْرَةٌ ', bengali: ' ফুল ', category: ' plant ', difficulty: 'easy' },
{ arabic:' غَابَةٌ ', bengali: ' বন ', category: ' nature ', difficulty: 'easy' },
{ arabic:' غُصْنٌ ', bengali: ' ডাল ', category: ' plant_part ', difficulty: 'easy' },
{ arabic:' فَاكِهَةٌ ', bengali: ' ফল ', category: ' food_drink ', difficulty: 'easy' },
{ arabic:' سَمَكَةٌ ', bengali: ' মাছ ', category: ' animal ', difficulty: 'easy' },
{ arabic:' مَيْدَانٌ ', bengali: ' মাঠ ', category: ' place ', difficulty: 'easy' },
{ arabic:' مَنْظَرٌ ', bengali: ' দৃশ্য ', category: ' vision ', difficulty: 'easy' },
{ arabic:' طَوِيلٌ ', bengali: ' লম্বা ', category: ' dimension ', difficulty: 'medium' },
{ arabic:' قَصِيرٌ ', bengali: ' খাটো ', category: ' dimension ', difficulty: 'medium' },
{ arabic:' لَذِيذٌ ', bengali: ' সুস্বাদু ', category: ' taste ', difficulty: 'easy' },
{ arabic:' سَرِيعٌ ', bengali: ' দ্রুতগামী ', category: ' speed ', difficulty: 'easy' },
{ arabic:' كَثِيرٌ ', bengali: ' বেশী ', category: ' quantity ', difficulty: 'easy' },
{ arabic:' ثَمِينٌ ', bengali: ' দামী ', category: ' value ', difficulty: 'easy' },
{ arabic:' قَلِيلٌ ', bengali: ' কম ', category: ' quantity ', difficulty: 'easy' },
{ arabic:' عَالٍ ', bengali: ' উঁচু ', category: ' dimension ', difficulty: 'easy' },
{ arabic:' حَارٌّ ', bengali: ' গরম ', category: ' temperature ', difficulty: 'easy' },
{ arabic:' رَخِيصٌ ', bengali: ' সস্তা ', category: ' value ', difficulty: 'easy' },
{ arabic:' بَارِدٌ ', bengali: ' ঠান্ডা ', category: ' temperature ', difficulty: 'easy' },
{ arabic:' فَاسِدٌ ', bengali: ' নষ্ট ', category: ' quality ', difficulty: 'medium' },
{ arabic:' بِخَيْرٍ ', bengali: ' ভালো আছে ', category: ' expression ', difficulty: 'medium' },
{ arabic:' جَاهِلٌ ', bengali: ' মূর্খ ', category: ' human_adj ', difficulty: 'easy' },
{ arabic:' لَكِنْ ', bengali: ' কিন্তু ', category: ' conjunction ', difficulty: 'easy' },
{ arabic:' مَظْلُومٌ ', bengali: ' অত্যাচারিত ', category: ' human_adj ', difficulty: 'easy' },
{ arabic:' مَتْحَفٌ ', bengali: ' জাদুঘর ', category: ' place ', difficulty: 'hard' },
{ arabic:' خَيْرٌ ', bengali: ' ভালো/কল্যাণকর ', category: ' quality ', difficulty: 'medium' },
{ arabic:' شَرٌّ ', bengali: ' মন্দ/খারাপ ', category: ' quality ', difficulty: 'medium' },
{ arabic:' ظَالِمٌ ', bengali: ' অত্যাচারী ', category: ' human_adj ', difficulty: 'easy' },
{ arabic:' مَكْتَبٌ ', bengali: ' ডেস্ক/অফিস ', category: ' place ', difficulty: 'easy' },
{ arabic:' بُنْدُقِيَّةٌ ', bengali: ' বন্দুক ', category: ' weapon ', difficulty: 'medium' },
{ arabic:' أَمْرٌ ', bengali: ' বিষয় ', category: ' concept ', difficulty: 'hard' },
{ arabic:' مُتَوَاضِعٌ ', bengali: ' বিনয়ী ', category: ' human_adj ', difficulty: 'easy' },
{ arabic:' مُتَكَبِّرٌ ', bengali: ' অহংকারী ', category: ' human_adj ', difficulty: 'easy' },
{ arabic:' خَادِمٌ ', bengali: ' সেবক ', category: ' profession ', difficulty: 'medium' },
{ arabic:' سَخِيٌّ ', bengali: ' দানশীল ', category: ' human_adj ', difficulty: 'hard' },
{ arabic:' بَخِيلٌ ', bengali: ' কৃপণ ', category: ' human_adj ', difficulty: 'medium' },
{ arabic:' صَيَّادٌ ', bengali: ' শিকারী ', category: ' profession ', difficulty: 'easy' },
{ arabic:' سَابِقٌ ', bengali: ' চালাক ', category: ' human_adj ', difficulty: 'medium' },
{ arabic:' صَادِقٌ ', bengali: ' সত্যবাদী ', category: ' human_adj ', difficulty: 'easy' },
{ arabic:' طَبَّاخٌ ', bengali: ' রাঁধুনি ', category: ' profession ', difficulty: 'medium' },
{ arabic:' عَالِمٌ ', bengali: ' জ্ঞানী ', category: ' human_adj ', difficulty: 'medium' },
{ arabic:' صَالِحٌ ', bengali: ' সৎ ', category: ' human_adj ', difficulty: 'medium' },
{ arabic:' خَبِيثٌ ', bengali: ' খারাপ ', category: ' human_adj ', difficulty: 'medium' },
{ arabic:' عَمِيقٌ ', bengali: ' গভীর ', category: ' dimension ', difficulty: 'medium' },
{ arabic:' عَظِيمٌ ', bengali: ' বিশাল ', category: ' dimension ', difficulty: 'medium' },
{ arabic:' مُسْلِمٌ ', bengali: ' মুসলিম ', category: ' religion ', difficulty: 'easy' },
{ arabic:' مُؤْمِنٌ ', bengali: ' মুমিন ', category: ' religion ', difficulty: 'easy' },
{ arabic:' طِفْلٌ ', bengali: ' শিশু ', category: ' person ', difficulty: 'easy' },
{ arabic:' طَبِيبٌ ', bengali: ' ডাক্তার ', category: ' profession ', difficulty: 'medium' },
{ arabic:' مَرِيضٌ ', bengali: ' রোগী ', category: ' health ', difficulty: 'medium' },
{ arabic:' نَشِيطٌ ', bengali: ' উদ্যমী ', category: ' human_adj ', difficulty: 'medium' },
{ arabic:' حَاسِدٌ ', bengali: ' হিংসুক ', category: ' human_adj ', difficulty: 'medium' },
{ arabic:' بَطِيءٌ ', bengali: ' ধীরগতি ', category: ' speed ', difficulty: 'hard' },
{ arabic:' رَاقٍ ', bengali: ' উন্নত ', category: ' state ', difficulty: 'hard' },
{ arabic:' رَائِقٌ ', bengali: ' পরিষ্কার ', category: ' state ', difficulty: 'hard' },
{ arabic:' لَا شَيْءٌ ', bengali: ' কিছু না ', category: ' expression ', difficulty: 'hard' },
{ arabic:' آسِفٌ ', bengali: ' দুঃখিত ', category: ' expression ', difficulty: 'hard' },
{ arabic:' مَاذَا ', bengali: ' কী ', category: ' question_word ', difficulty: 'easy' },
{ arabic:' كَيْفَ ', bengali: ' কেমন? ', category: ' question_word ', difficulty: 'easy' },
{ arabic:' هُنَاكَ ', bengali: ' সেখানে ', category: ' location ', difficulty: 'easy' },
{ arabic:' هُنَا ', bengali: ' এখানে ', category: ' location ', difficulty: 'easy' },
{ arabic:' حَسَنًا ', bengali: ' ভালো ', category: ' expression ', difficulty: 'medium' },
{ arabic:' مَا بِكَ؟ ', bengali: ' তোমার কী হয়েছে? ', category: ' question ', difficulty: 'medium' },
{ arabic:' تَاجِرٌ ', bengali: ' ব্যবসায়ী ', category: ' profession ', difficulty: 'easy' },
{ arabic:' فَلَّاحٌ ', bengali: ' কৃষক ', category: ' profession ', difficulty: 'easy' },
{ arabic:' غَنِيٌّ ', bengali: ' ধনী ', category: ' status ', difficulty: 'medium' },
{ arabic:' فَقِيرٌ ', bengali: ' দরিদ্র ', category: ' status ', difficulty: 'easy' },
{ arabic:' ذَكِيٌّ ', bengali: ' মেধাবী ', category: ' intelligence ', difficulty: 'medium' },
{ arabic:' غَبِيٌّ ', bengali: ' নির্বোধ ', category: ' intelligence ', difficulty: 'medium' },
{ arabic:' ضَعِيفٌ ', bengali: ' দুর্বল ', category: ' strength ', difficulty: 'easy' },
{ arabic:' مُجْتَهِدٌ ', bengali: ' পরিশ্রমী ', category: ' human_adj ', difficulty: 'easy' },
{ arabic:' مَاهِرٌ ', bengali: ' দক্ষ ', category: ' human_adj ', difficulty: 'easy' },
{ arabic:' مَشْهُورٌ ', bengali: ' প্রসিদ্ধ ', category: ' status ', difficulty: 'easy' },
{ arabic:' قَوِيٌّ ', bengali: ' মজবুত ', category: ' strength ', difficulty: 'easy' },
{ arabic:' صَدِيقٌ ', bengali: ' বন্ধু ', category: ' relationship ', difficulty: 'easy' },
{ arabic:' عَدُوٌّ ', bengali: ' শত্রু ', category: ' relationship ', difficulty: 'easy' },
{ arabic:' طَيِّبٌ ', bengali: ' উত্তম ', category: ' quality ', difficulty: 'hard' },
{ arabic:' جِدًّا ', bengali: ' খুব ', category: ' intensity ', difficulty: 'easy' },
{ arabic:' قَبِيحٌ ', bengali: ' অসুন্দর ', category: ' appearance ', difficulty: 'easy' },
{ arabic:' جَدِيدٌ ', bengali: ' নতুন ', category: ' time_quality ', difficulty: 'easy' },
{ arabic:' قَدِيمٌ ', bengali: ' পুরাতন ', category: ' time_quality ', difficulty: 'easy' },
{ arabic:' جَيِّدٌ ', bengali: ' ভালো ', category: ' quality ', difficulty: 'easy' },
{ arabic:' جَمِيلٌ ', bengali: ' সুন্দর ', category: ' appearance ', difficulty: 'easy' },
{ arabic:' كَبِيرٌ ', bengali: ' বড় ', category: ' size ', difficulty: 'easy' },
{ arabic:' صَغِيرٌ ', bengali: ' ছোট ', category: ' size ', difficulty: 'easy' },
{ arabic:' نَظِيفٌ ', bengali: ' পরিচ্ছন ', category: ' cleanliness ', difficulty: 'medium' },
{ arabic:' قَذِرٌ ', bengali: ' ময়লা ', category: ' cleanliness ', difficulty: 'easy' },
{ arabic:' مَفْتُوحٌ ', bengali: ' খোলা ', category: ' state ', difficulty: 'easy' },
{ arabic:' مُغْلَقٌ ', bengali: ' বন্ধ ', category: ' state ', difficulty: 'easy' },
{ arabic:' وَاسِعٌ ', bengali: ' প্রশস্ত ', category: ' dimension ', difficulty: 'easy' },
{ arabic:' ضَيِّقٌ ', bengali: ' সংকীর্ণ ', category: ' dimension ', difficulty: 'medium' },
{ arabic:' شَرِيفٌ ', bengali: ' সম্মানিত ', category: ' status ', difficulty: 'medium' },
{ arabic:' مُؤَدِّبٌ ', bengali: ' সভ্য ', category: ' behavior ', difficulty: 'easy' },
{ arabic:' وَسِخٌ ', bengali: ' ময়লা ', category: ' cleanliness ', difficulty: 'easy' },
{ arabic:' كَسْلَانٌ ', bengali: ' অলস ', category: ' human_adj ', difficulty: 'easy' },
{ arabic:' هَذَا ', bengali: ' ইহা ', category: ' demonstrative ', difficulty: 'easy' },
{ arabic:' ذَلِكَ ', bengali: ' ওটা ', category: ' demonstrative ', difficulty: 'easy' },
{ arabic:' مَدْرَسَةٌ ', bengali: '  মাদরাসা ', category: ' place ', difficulty: 'easy' },
{ arabic:' كِتَابٌ ', bengali: '  বই ', category: ' object ', difficulty: 'easy' },
{ arabic:' سَبُّوْرَةٌ ', bengali: '  রাকবোর্ড ', category: ' object ', difficulty: 'easy' },
{ arabic:' مَسْجِدٌ ', bengali: '  মসজিদ ', category: ' place ', difficulty: 'easy' },
{ arabic:' نَافِذَةٌ ', bengali: '  জানালা ', category: ' house_part ', difficulty: 'easy' },
{ arabic:' مِصْبَاحٌ ', bengali: '  বাতি ', category: ' object ', difficulty: 'easy' },
{ arabic:' كُرَّاسَةٌ ', bengali: '  খাতা ', category: ' object ', difficulty: 'easy' },
{ arabic:' قَلَمٌ ', bengali: '  কলম ', category: ' object ', difficulty: 'easy' },
{ arabic:' حَقِيْبَةٌ ', bengali: '  ব্যাগ ', category: ' object ', difficulty: 'easy' },
{ arabic:' سَرِيْرٌ ', bengali: '  খাট ', category: ' furniture ', difficulty: 'easy' },
{ arabic:' سَاعَةٌ ', bengali: '  ঘড়ি ', category: ' object ', difficulty: 'easy' },
{ arabic:' مِفْتَاحٌ ', bengali: '  চাবি ', category: ' object ', difficulty: 'easy' },
{ arabic:' مِظَلَّةٌ ', bengali: '  ছাতা ', category: ' object ', difficulty: 'easy' },
{ arabic:' جِدَارٌ ', bengali: '  দেয়াল ', category: ' house_part ', difficulty: 'easy' },
{ arabic:' طَاوِلَةٌ ', bengali: '  টেবিল ', category: ' furniture ', difficulty: 'easy' },
{ arabic:' طَرِيْقٌ ', bengali: '  পথ ', category: ' place ', difficulty: 'easy' },
{ arabic:' مِرْوَحَةٌ ', bengali: '  ফ্যান ', category: ' object ', difficulty: 'easy' },
{ arabic:' صَحْنٌ ', bengali: '  থালা ', category: ' kitchenware ', difficulty: 'hard' },
{ arabic:' حُجْرَةٌ ', bengali: '  কক্ষ ', category: ' house_part ', difficulty: 'easy' },
{ arabic:' كُوْبٌ ', bengali: '  গ্লাস ', category: ' kitchenware ', difficulty: 'easy' },
{ arabic:' مِسْطَرَةٌ ', bengali: '  রুলার ', category: ' object ', difficulty: 'easy' },
{ arabic:' إِبْرِيْقٌ ', bengali: '  জগ ', category: ' kitchenware ', difficulty: 'medium' },
{ arabic:' نَظَّارَةٌ ', bengali: '  চশমা ', category: ' accessory ', difficulty: 'easy' },
{ arabic:' كُرْسِيٌّ ', bengali: '  চেয়ার ', category: ' furniture ', difficulty: 'easy' },
{ arabic:' مِلْعَقَةٌ ', bengali: '  চামচ ', category: ' kitchenware ', difficulty: 'easy' },
{ arabic:' بَابٌ ', bengali: '  দরজা ', category: ' house_part ', difficulty: 'easy' },
{ arabic:' طَائِرَةٌ ', bengali: '  বিমান ', category: ' transport ', difficulty: 'hard' },
{ arabic:' فِنْجَانٌ ', bengali: '  কাপ ', category: ' kitchenware ', difficulty: 'easy' },
{ arabic:' دَرَّاجَةٌ ', bengali: '  সাইকেল ', category: ' transport ', difficulty: 'easy' },
{ arabic:' قُفْلٌ ', bengali: '  তালা ', category: ' object ', difficulty: 'easy' },
{ arabic:' سَيَّارَةٌ ', bengali: '  গাড়ি ', category: ' transport ', difficulty: 'easy' },
{ arabic:' بَيْتٌ ', bengali: '  ঘর ', category: ' place ', difficulty: 'easy' },
{ arabic:' سَفِينَةٌ ', bengali: '  জাহাজ ', category: ' transport ', difficulty: 'hard' },
{ arabic:' سُلَّمٌ ', bengali: '  সিঁড়ি ', category: ' house_part ', difficulty: 'hard' },
{ arabic:' مَدِينَةٌ ', bengali: '  শহর ', category: ' place ', difficulty: 'easy' },
{ arabic:' مَطْبَخٌ ', bengali: '  রান্নাঘর ', category: ' house_part ', difficulty: 'hard' },
{ arabic:' مِمْسَاحَةٌ ', bengali: '  পাপোশ ', category: ' object ', difficulty: 'hard' },
{ arabic:' قَمِيصٌ ', bengali: '  জামা ', category: ' clothing ', difficulty: 'easy' },
{ arabic:' دَوَاةٌ ', bengali: ' দোয়াত ', category: ' object ', difficulty: 'hard' },
{ arabic:' ثَوْبٌ ', bengali: '  কাপড় ', category: ' clothing ', difficulty: 'medium' },
{ arabic:' قَلَنْسُوَةٌ ', bengali: '  টুপি ', category: ' clothing ', difficulty: 'easy' },
{ arabic:' جَبَلٌ ', bengali: '  পাহাড় ', category: ' nature ', difficulty: 'easy' },
{ arabic:' وِسَادَةٌ ', bengali: '  বালিশ ', category: ' house_part ', difficulty: 'medium' },
{ arabic:' فِرَاشٌ ', bengali: '  বিছানা ', category: ' furniture ', difficulty: 'easy' },
{ arabic:' حَدِيقَةٌ ', bengali: '  বাগান ', category: ' place ', difficulty: 'easy' },
{ arabic:' حِذَاءٌ ', bengali: '  জুতা ', category: ' clothing ', difficulty: 'easy' },
{ arabic:' قَرْيَةٌ ', bengali: '  গ্রাম ', category: ' place ', difficulty: 'easy' },
{ arabic:' عَلَمٌ ', bengali: '  পতাকা ', category: ' object ', difficulty: 'easy' },
{ arabic:' دَبَّابَةٌ ', bengali: '  ট্যাঙ্ক ', category: ' weapon ', difficulty: 'medium' },
{ arabic:' حِبْرٌ ', bengali: ' কালি ', category: ' object ', difficulty: 'medium' },
{ arabic:' صَفْحَةٌ ', bengali: '  পৃষ্ঠা ', category: ' object ', difficulty: 'medium' },
{ arabic:' مِنْدِيلٌ ', bengali: '  রুমাল ', category: ' object ', difficulty: 'easy' },
{ arabic:' لُغَةٌ ', bengali: ' ভাষা ', category: ' language ', difficulty: 'medium' },
{ arabic:' لِبَاسٌ ', bengali: '  পোশাক ', category: ' clothing ', difficulty: 'easy' },
{ arabic:' بِنْتٌ ', bengali: '  মেয়ে ', category: ' person ', difficulty: 'easy' },
{ arabic:' وَلَدٌ ', bengali: '  ছেলে ', category: ' person ', difficulty: 'medium' },
{ arabic:' اِمْرَأَةٌ ', bengali: '  মহিলা ', category: ' person ', difficulty: 'easy' },
{ arabic:' رَجُلٌ ', bengali: '  পুরুষ ', category: ' person ', difficulty: 'easy' },
{ arabic:' تِلْمِيذٌ ', bengali: '  ছাত্র ', category: ' profession ', difficulty: 'easy' },
{ arabic:' مُعَلِّمٌ ', bengali: '  শিক্ষক ', category: ' profession ', difficulty: 'easy' },
{ arabic:' أَمْ ', bengali: ' নাকি, না ', category: ' conjunction ', difficulty: 'hard' },
{ arabic:' وَ ', bengali: ' এবং / আর / ও ', category: ' conjunction ', difficulty: 'hard' },
{ arabic:' أَيْضًا ', bengali: ' ও ', category: ' expression ', difficulty: 'hard' },
{ arabic:' بَلْ ', bengali: ' বরং ', category: ' conjunction ', difficulty: 'hard' },
{ arabic:' مِنْ فَضْلِكَ ', bengali: ' প্রিয়, দয়া করে ... ', category: ' expression ', difficulty: 'hard' },
{ arabic:' مَاءٌ ', bengali: ' পানি ', category: ' food_drink ', difficulty: 'medium' },
{ arabic:' لَيْلَةٌ سَعِيدَةٌ ', bengali: ' শুভ রাত্রি ', category: ' expression ', difficulty: 'hard' },
{ arabic:' شُكْرًا ', bengali: ' ধন্যবাদ ', category: ' expression ', difficulty: 'hard' },
{ arabic:' إِلَى اللِّقَاءِ ', bengali: ' আবার দেখা হবে ', category: ' expression ', difficulty: 'hard' },
{ arabic:' مَعَ السَّلَامَةِ ', bengali: ' বিদায়  ', category: ' expression ', difficulty: 'hard' },
{ arabic:' أَمَةٌ ', bengali: ' দাসী, বান্দি ', category: ' status ', difficulty: 'medium' },
{ arabic:' غِلَافٌ ', bengali: ' গিলাফ ', category: ' object ', difficulty: 'easy' },
{ arabic:' مَعْبَدٌ ', bengali: ' মন্দির ', category: ' place ', difficulty: 'medium' },
{ arabic:' عَبْدٌ ', bengali: ' দাস, বান্দা ', category: ' status ', difficulty: 'easy' },
{ arabic:' أَيْنَ ', bengali: ' কোথায় ', category: ' question_word ', difficulty: 'easy' },
{ arabic:' مَنْطَقَةٌ ', bengali: ' এলাকা ', category: ' place ', difficulty: 'hard' },
{ arabic:' مُشْكِلَةٌ ', bengali: ' সমস্যা ', category: ' concept ', difficulty: 'hard' },
{ arabic:' وَسَطٌ ', bengali: ' মধ্যভাগ ', category: ' position ', difficulty: 'hard' },
{ arabic:' فَرِيضَةٌ ', bengali: ' ফরজ ', category: ' islamic_concept ', difficulty: 'hard' },
{ arabic:' وَعْدٌ ', bengali: ' প্রতিশ্রুতি ', category: ' expression ', difficulty: 'hard' },
{ arabic:' رَأْسٌ ', bengali: ' মাথা/মুণ্ড ', category: ' body_part ', difficulty: 'easy' },
{ arabic:' خِيَانَةٌ ', bengali: ' বিশ্বাসঘাতকতা ', category: ' concept ', difficulty: 'easy' },
{ arabic:' طُمَأْنِيْنَةٌ ', bengali: ' প্রশান্তি ', category: ' state ', difficulty: 'hard' },
{ arabic:' إِثْمٌ ', bengali: ' পাপ ', category: ' sin ', difficulty: 'hard' },
{ arabic:' خَطِيْئَةٌ ', bengali: ' ভুল ', category: ' sin ', difficulty: 'hard' },
{ arabic:' دَارٌ ', bengali: ' বাড়ি ', category: ' place ', difficulty: 'medium' },
{ arabic:' رِيْبَةٌ/شَكٌّ ', bengali: ' সন্দেহ ', category: ' concept ', difficulty: 'hard' },
{ arabic:' كَهْرَبَاءٌ ', bengali: ' বিদ্যুৎ ', category: ' nature/energy ', difficulty: 'hard' },
{ arabic:' حُبٌّ ', bengali: ' ভালোবাসা ', category: ' emotion ', difficulty: 'easy' },
{ arabic:' دُعَاءٌ ', bengali: ' দোয়া ', category: ' islamic_concept ', difficulty: 'medium' },
{ arabic:' خَمْرٌ ', bengali: ' মদ ', category: ' object ', difficulty: 'easy' },
{ arabic:' مُسْتَشْفٰى ', bengali: ' হাসপাতাল ', category: ' place ', difficulty: 'medium' },
{ arabic:' لَئِيْمٌ ', bengali: ' দুষ্ট/ইতর ', category: ' human_adj ', difficulty: 'hard' },
{ arabic:' حُجَّةٌ/بُرْهَانٌ ', bengali: ' দলিল ', category: ' concept ', difficulty: 'hard' },
{ arabic:' فَمٌ ', bengali: ' মুখ ', category: ' body_part ', difficulty: 'medium' },
{ arabic:' مَجَلَّةٌ ', bengali: ' পত্রিকা ', category: ' object ', difficulty: 'hard' },
{ arabic:' زَمِيلٌ ', bengali: ' সহপাঠী ', category: ' relationship ', difficulty: 'medium' },
{ arabic:' مِحْرَاثٌ ', bengali: ' লাঙ্গল ', category: ' object ', difficulty: 'easy' },
{ arabic:' مَكْسُورٌ ', bengali: ' ভাঙা ', category: ' state ', difficulty: 'medium' },
{ arabic:' مِنْ ', bengali: ' থেকে ', category: ' preposition ', difficulty: 'easy' },
{ arabic:' مَعَ ', bengali: ' সাথে ', category: ' preposition ', difficulty: 'easy' },
{ arabic:' ب ', bengali: ' দ্বারা/মাধ্যমে ', category: ' preposition ', difficulty: 'easy' },
{ arabic:' عَلَى ', bengali: ' উপরে ', category: ' preposition ', difficulty: 'easy' },
{ arabic:' فِي ', bengali: ' মধ্যে ', category: ' preposition ', difficulty: 'easy' },
{ arabic:' لِ ', bengali: ' জন্য ', category: ' preposition ', difficulty: 'easy' },
{ arabic:' حَتَّى ', bengali: ' পর্যন্ত ', category: ' preposition ', difficulty: 'easy' },
{ arabic:' إِلَى ', bengali: ' দিকে/পর্যন্ত ', category: ' preposition ', difficulty: 'easy' },
{ arabic:' قَبْلَ ', bengali: ' আগে ', category: ' time ', difficulty: 'easy' },
{ arabic:' بَعْدَ ', bengali: ' পরে ', category: ' time ', difficulty: 'easy' },
{ arabic:' يَوْمِيٌّ ', bengali: ' দৈনিক ', category: ' time ', difficulty: 'hard' },
{ arabic:' شَهْرِيٌّ ', bengali: ' মাসিক ', category: ' time ', difficulty: 'hard' },
{ arabic:' الآن ', bengali: ' এখন ', category: ' time ', difficulty: 'hard' },
{ arabic:' دَائِمًا ', bengali: ' সর্বদা ', category: ' time ', difficulty: 'hard' },
{ arabic:' لَيْلٌ ', bengali: ' রাত ', category: ' time ', difficulty: 'hard' },
{ arabic:' نَهَارٌ ', bengali: ' দিন ', category: ' time ', difficulty: 'hard' },
{ arabic:' صَبَاحٌ ', bengali: ' সকাল ', category: ' time ', difficulty: 'hard' },
{ arabic:' مَسَاءٌ ', bengali: ' সন্ধ্যা ', category: ' time ', difficulty: 'hard' },
{ arabic:' بَعْدَ قَلِيلٍ ', bengali: ' কিছুক্ষণ পরে ', category: ' time ', difficulty: 'hard' },
{ arabic:' قَبْلَ قَلِيلٍ ', bengali: ' কিছুক্ষণ পূর্বে ', category: ' time ', difficulty: 'hard' },
{ arabic:' فَصْلٌ ', bengali: ' শ্রেণিকক্ষ ', category: ' place ', difficulty: 'easy' },
{ arabic:' كُرَةٌ ', bengali: '  বল ', category: ' object ', difficulty: 'easy' },
{ arabic:' يَمِينٌ ', bengali: ' ডান ', category: ' direction ', difficulty: 'easy' },
{ arabic:' سَهْمٌ ', bengali: '  তীর ', category: ' weapon ', difficulty: 'medium' },
{ arabic:' شِمَالٌ ', bengali: ' বাম ', category: ' direction ', difficulty: 'easy' },
{ arabic:' قُنْبُلَةٌ ', bengali: '  বোমা ', category: ' weapon ', difficulty: 'easy' },
{ arabic:' نَارٌ ', bengali: ' আগুন ', category: ' nature ', difficulty: 'easy' },
{ arabic:' مُسْتَوْصَفٌ ', bengali: ' ক্লিনিক ', category: ' place ', difficulty: 'hard' },
{ arabic:' عَمُودٌ ', bengali: ' খুঁটি, স্তম্ভ ', category: ' object ', difficulty: 'hard' },
{ arabic:' قَوْسٌ ', bengali: ' ধনুক ', category: ' weapon ', difficulty: 'hard' },
{ arabic:' مِوقِدٌ ', bengali: '  চুলা ', category: ' kitchenware ', difficulty: 'hard' },
{ arabic:' فِنَاءٌ ', bengali: ' আঙিনা ', category: ' place ', difficulty: 'hard' },
{ arabic:' طَازَجٌ / طَازَةٌ ', bengali: ' তাজা ', category: ' quality ', difficulty: 'easy' },
{ arabic:' سِتَارَةٌ ', bengali: ' পর্দা ', category: ' object ', difficulty: 'hard' },
{ arabic:' سَجَّادَةٌ ', bengali: ' গালিচা ', category: ' object ', difficulty: 'hard' },
{ arabic:' بَائِتٌ ', bengali: ' বাসি ', category: ' quality ', difficulty: 'hard' },
{ arabic:' عَسَلٌ ', bengali: ' মধু ', category: ' food_drink ', difficulty: 'medium' },
{ arabic:' مَسَّاحَةٌ ', bengali: ' ডাস্টার ', category: ' object ', difficulty: 'medium' },
{ arabic:' خَارِطَةٌ ', bengali: ' ম্যাপ ', category: ' object ', difficulty: 'easy' },
{ arabic:' قِصَّةٌ ', bengali: ' গল্প, ঘটনা ', category: ' concept ', difficulty: 'easy' },
{ arabic:' لَاعِبٌ ', bengali: '  খেলোয়াড় ', category: ' profession ', difficulty: 'easy' },
{ arabic:' قَلْبٌ ', bengali: ' হৃদয়, মন ', category: ' body_part ', difficulty: 'easy' },
{ arabic:' حُلْوٌ ', bengali: ' মিষ্টি ', category: ' taste ', difficulty: 'easy' },
{ arabic:' يَدٌ ', bengali: ' হাত ', category: ' body_part ', difficulty: 'easy' },
{ arabic:' حَامِضٌ ', bengali: ' টক ', category: ' taste ', difficulty: 'easy' },
{ arabic:' سِوَارٌ ', bengali: ' চুড়ি, বালা ', category: ' accessory ', difficulty: 'hard' },
{ arabic:' رِجْلٌ ', bengali: ' পা ', category: ' body_part ', difficulty: 'hard' },
{ arabic:' مَتَى ', bengali: ' কখন ', category: ' question_word ', difficulty: 'hard' },
{ arabic:' مِنْ مَتَى ', bengali: ' কখন থেকে? ', category: ' question_word ', difficulty: 'hard' },
{ arabic:' إِلَى مَتَى ', bengali: ' কতক্ষণ ', category: ' question_word ', difficulty: 'hard' },
{ arabic:' عَلَى مَاذَا ', bengali: ' কিসের ওপর ', category: ' question_word ', difficulty: 'hard' },
{ arabic:' لِمَاذَا ', bengali: ' কেন ', category: ' question_word ', difficulty: 'hard' },
{ arabic:' مِنْ أَيْنَ ', bengali: ' কোথেকে ', category: ' question_word ', difficulty: 'hard' },
{ arabic:' إِلَى أَيْنَ ', bengali: ' কোন দিকে ', category: ' question_word ', difficulty: 'hard' },
{ arabic:' كَمْ ', bengali: ' কতো? ', category: ' question_word ', difficulty: 'hard' },
{ arabic:' هٰا) أَنَا) ', bengali: ' এই তো (আমি) ', category: ' demonstrative ', difficulty: 'hard' },
{ arabic:' مَعْذِرَةً ', bengali: ' ক্ষমা চাই ', category: ' expression ', difficulty: 'hard' },
{ arabic:' حَيَوَانٌ ', bengali: '  প্রাণী ', category: ' animal ', difficulty: 'easy' },
{ arabic:' لِسَانٌ ', bengali: ' জিহ্বা ', category: ' body_part ', difficulty: 'easy' },
{ arabic:' شَعْرٌ ', bengali: ' চুল ', category: ' body_part ', difficulty: 'hard' },
{ arabic:' وَجْهٌ ', bengali: ' মুখ, চেহারা ', category: ' body_part ', difficulty: 'easy' },
{ arabic:' عَيْنٌ ', bengali: ' চোখ ', category: ' body_part ', difficulty: 'easy' },
{ arabic:' خَدٌّ ', bengali: ' গাল ', category: ' body_part ', difficulty: 'easy' },
{ arabic:' بَطْنٌ ', bengali: ' পেট ', category: ' body_part ', difficulty: 'easy' },
{ arabic:' ظَهْرٌ ', bengali: ' পিঠ ', category: ' body_part ', difficulty: 'easy' },
{ arabic:' ظِلٌّ ', bengali: ' ছায়া ', category: ' nature ', difficulty: 'medium' },
{ arabic:' مَكْتَبَةٌ ', bengali: ' পাঠাগার, লাইব্রেরি ', category: ' place ', difficulty: 'medium' },
{ arabic:' نَمِرٌ ', bengali: '  বাঘ ', category: ' animal ', difficulty: 'medium' },
{ arabic:' كَلْبٌ ', bengali: '  কুকুর ', category: ' animal ', difficulty: 'easy' },
{ arabic:' جِسْمٌ ', bengali: ' শরীর ', category: ' body_part ', difficulty: 'hard' },
{ arabic:' قِرْدٌ ', bengali: '  বানর ', category: ' animal ', difficulty: 'easy' },
{ arabic:' غُرَابٌ ', bengali: '  কাক ', category: ' animal ', difficulty: 'medium' },
{ arabic:' ذِئْبٌ ', bengali: '  নেকড়ে ', category: ' animal ', difficulty: 'hard' },
{ arabic:' ظَبْيٌ ', bengali: '  হরিণ ', category: ' animal ', difficulty: 'hard' },
{ arabic:' فِيلٌ ', bengali: '  হাতি ', category: ' animal ', difficulty: 'medium' },
{ arabic:' عُصْفُورَةٌ ', bengali: '  চড়ুই ', category: ' animal ', difficulty: 'easy' },
{ arabic:' فَأْرٌ ', bengali: ' ইঁদুর ', category: ' animal ', difficulty: 'medium' },
{ arabic:' أَسَدٌ ', bengali: ' সিংহ ', category: ' animal ', difficulty: 'easy' },
{ arabic:' صَدْرٌ ', bengali: ' বুক ', category: ' body_part ', difficulty: 'medium' },
{ arabic:' غِذَاءٌ ', bengali: ' খাদ্য ', category: ' food_drink ', difficulty: 'hard' },
{ arabic:' نَهْرٌ ', bengali: '  নদী ', category: ' nature ', difficulty: 'medium' },
{ arabic:' بَحْرٌ ', bengali: '  সমুদ্র ', category: ' nature ', difficulty: 'medium' },
{ arabic:' حِمَارٌ ', bengali: '  গাধা ', category: ' animal ', difficulty: 'easy' },
{ arabic:' جِسْرٌ ', bengali: ' ব্রিজ ', category: ' food_drink ', difficulty: 'hard' },
{ arabic:' تَمْرَةٌ ', bengali: '  খেজুর ', category: ' food_drink ', difficulty: 'hard' },
{ arabic:' غَدِيرٌ ', bengali: '  পুকুর ', category: ' nature ', difficulty: 'hard' },
{ arabic:' إِنَّ ', bengali: ' নিশ্চয় ', category: ' expression ', difficulty: 'hard' },
{ arabic:' لٰكِنَّ ', bengali: ' কিন্তু ', category: ' conjunction ', difficulty: 'hard' },
{ arabic:' أَنَّ ', bengali: ' নিশ্চয় ', category: ' expression ', difficulty: 'hard' },
{ arabic:' كَأَنَّ ', bengali: ' যেন ', category: ' expression ', difficulty: 'hard' },
{ arabic:' لَعَلَّ ', bengali: ' মনে হয়, সম্ভবত ', category: ' expression ', difficulty: 'hard' },
{ arabic:' لَيْتَ ', bengali: ' হায় যদি! ', category: ' expression ', difficulty: 'hard' },














  ];

  // In your parent component

  return (
    <div>
      <Vocabulary vocabulary={vocabularyData} />
    </div>
  )
}

export default App
